name: Publish Docker image

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [publish-docker-image]
  workflow_dispatch:

env:
  IMAGE: lobometalurgico/arunacore

jobs:
  build-and-publish:
    name: Build, test and publish Docker images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant:
          - name: slim
            dockerfile: Dockerfile
            tag-suffix: ""
          - name: alpine
            dockerfile: Dockerfile-alpine
            tag-suffix: -alpine

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest arunacore version from GitHub
        id: get_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ArunaBot/ArunaCore
          excludes: draft

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}}{{matrix.variant.tag-suffix}}
            type=sha,prefix=,suffix={{matrix.variant.tag-suffix}}
        env:
          version: ${{ steps.get_version.outputs.release }}

      # === Build and test image ===
      - name: Build image for testing
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.variant.dockerfile }}
          load: true
          tags: ${{ env.IMAGE }}:test-${{ matrix.variant.name }}
        env:
          VERSION: ${{ steps.get_version.outputs.release }}

      - name: Run smoke test
        run: |
          docker run --env ARUNACORE_FINISH_IN_SECONDS=10 --rm ${{ env.IMAGE }}:test-${{ matrix.variant.name }}

      # === Push if tests pass ===
      - name: Push production image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.variant.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:latest${{ matrix.variant.tag-suffix }}
            ${{ env.IMAGE }}:${{ steps.get_version.outputs.release }}${{ matrix.variant.tag-suffix }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          VERSION: ${{ steps.get_version.outputs.release }}

  # Atualiza descrição uma vez após builds
  update-description:
    name: Update Docker Hub description
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE }}
